### ISSUE TITLE
OAS 3.0: BLOB and contentEncoding

### ISSUE THREAD

**Issue by lamuertepeluda** [alt3/sequelize-to-json-schemas#76]
Hi there

When validating a schema generated with the OAS 3.0 strategy I get the follwing error

`Property contentEncoding is not allowed.`

The original field looks like

```js
  recording: {
    type: DataTypes.BLOB('long'),
    defaultValue: null,
  },
```

The generated is

```yml
        recording:
          type: string
          contentEncoding: base64
          nullable: true
          default: null
```

Maybe the problem [is at this line](https://github.com/alt3/sequelize-to-json-schemas/blob/0fc2c4c375cc4167911227e8e244446cb6c1ab6d/lib/type-mapper.js#L78)

According to https://swagger.io/docs/specification/data-models/data-types/#format

I would imagine something like

```yml
        recording:
          type: string
          format: byte
          nullable: true
          default: null
```

that means changing the line of code mentioned into

```js
      case 'BLOB': {
        result = { ...STRING, format: 'byte' };
        break;
      }
```

at least for the openapi strategy. Am I right?
